### ISSUE TITLE
[coc.nvim] RPC: TypeError: e.forEach is not a function error

### ISSUE THREAD

**Issue by BooleanCube** [leonardssh/coc-discord-rpc#64] opened 2022-07-24 13:04 UTC
I recently saw another issue opened with the same error and it was flagged as resolved and so I reinstalled the coc-discord-rpc extension on coc.nvim but the error still pops up everytime I open up neovim.

The error: 
`[coc.nvim] RPC: TypeError: e.forEach is not a function`

**Comment by leonardssh** [comment] 2022-07-24 13:35
A new version of the extension has not yet been released. Soon™️

**Comment by BooleanCube** [comment] 2022-07-26 18:44
When do you think it will be released?

**Comment by leonardssh** [comment] 2022-07-26 20:06
ASAP. @BooleanCube

**Comment by SirCharlieMars** [comment] 2022-08-25 14:52
Is there the community can do to help?

**Comment by BooleanCube** [comment] 2022-08-28 15:11
Any news? This bug still hasn't been fixed and its been over a month..

**Comment by samuelolagunju** [comment] 2022-10-02 17:25
It's now October and the repo hasn't been updated since July... The repo is pretty much dead for now :(

**Comment by leonardssh** [comment] 2022-10-05 18:09
@samuelolagunju hey, the repo is not dead, I'm still here, but I don't have time to deal with the extension. I'm thinking of archiving the project, there are already similar projects much better done. i.e [presence.nvim](https://github.com/andweeb/presence.nvim) by @andweeb

@xhayper maybe you want to continue the project? If so, I'll transfer you the whole repo, just let me know.

**Comment by SirCharlieMars** [comment] 2022-10-05 18:11
I like this extension because it's connected to Coc, making it easy for me to use. I also really love the images this extension uses for its languages and editor.

**Comment by xhayper** [comment] 2022-10-07 08:26
@leonardssh i can continue the project

**Comment by xhayper** [comment] 2022-10-07 14:55
Can you guys try installing `leonardssh/coc-discord-rpc#build-dev` version of the extenstion? It should fix this bug, if it did then i will publish it.

Windows:
`%appdata%\..\Local\coc\extensions`

macOS:
not sure

Linux:
not sure

**Comment by SirCharlieMars** [comment] 2022-10-07 15:06
I'm on macOS and I get this:


<img wid/th="603" alt="CleanShot 2022-10-07 at 10 04 40@2x" src="https://user-images.githubusercontent.com/31679231/194585653-678f0bfe-7b0b-4a42-9e35-b9dedc02812b.png">


```
2022-10-07T10:04:39.177 INFO (pid:21765) [coc-discord-rpc] - === Extension activated ===
2022-10-07T10:04:39.178 INFO (pid:21765) [coc-discord-rpc] - Extension Name: dev.coc-discord-rpc.
2022-10-07T10:04:39.178 INFO (pid:21765) [coc-discord-rpc] - Extension Version: 0.0.0.
2022-10-07T10:04:39.187 INFO (pid:21765) [plugin] - coc.nvim initialized with node: v16.16.0 after 617ms
2022-10-07T10:04:39.198 ERROR (pid:21765) [server] - unhandledRejection  Promise {
  <rejected> RPC_COULD_NOT_CONNECT: Could not connect
      at /Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:108:20
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 2
  }
} RPC_COULD_NOT_CONNECT: Could not connect
    at /Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:108:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2
}
2022-10-07T10:04:39.483 INFO (pid:21765) [attach] - receive notification: highlight []
2022-10-07T10:04:49.179 ERROR (pid:21765) [coc-discord-rpc] - RPC_CONNECTION_TIMEOUT: Connection timed out
    at Client.login (/Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/Client.js:232:20)
    at Function.login (/Users/charlie/.config/coc/extensions/node_modules/coc-discord-rpc/dist/client.js:24:40)
    at Object.activate (/Users/charlie/.config/coc/extensions/node_modules/coc-discord-rpc/dist/index.js:84:41)
    at /Users/charlie/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:255:25905
    at new Promise (<anonymous>)
    at Object.activate (/Users/charlie/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:255:25508)
    at cS.autoActiavte (/Users/charlie/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:255:24748)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 1
}
2022-10-07T10:05:28.355 INFO (pid:21765) [attach] - receive notification: showInfo []
```

**Comment by xhayper** [comment] 2022-10-07 15:10
this is really weird, give me a moment while i debug this on my mac machine

**Comment by SirCharlieMars** [comment] 2022-10-07 15:16
Can i ask how you installed it? I went to `coc/extensions/node_modules` and did  `npm install leonardssh/coc-discord-rpc#build-dev`

**Comment by xhayper** [comment] 2022-10-07 15:16
can you go to `/Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transports/IPC.js` and add `console.log(socketPath)` to line 86

**Comment by xhayper** [comment] 2022-10-07 15:17
oh, edit your package.json

**Comment by SirCharlieMars** [comment] 2022-10-07 15:17
this is my package.json:

```json
{
  "dependencies": {
    "coc-clangd": ">=0.25.0",
    "coc-css": ">=1.3.0",
    "coc-discord-rpc": "github:leonardssh/coc-discord-rpc#build-dev",
    "coc-emmet": ">=1.1.6",
    "coc-java": ">=1.5.5",
    "coc-json": ">=1.6.1",
    "coc-lua": ">=1.0.1",
    "coc-pyright": ">=1.1.271",
    "coc-rust-analyzer": ">=0.68.1",
    "coc-sh": ">=0.7.0",
    "coc-snippets": ">=3.1.2",
    "coc-texlab": ">=3.2.0",
    "coc-tsserver": ">=1.11.9",
    "coc-vimlsp": ">=0.12.8",
    "coc-word": ">=1.2.2"
  },
  "disabled": [],
  "locked": [],
  "lastUpdate": 1665155687261
}
```

**Comment by xhayper** [comment] 2022-10-07 15:18
<img width="612" alt="Screenshot 2022-10-04 at 23 45 07" src="https://user-images.githubusercontent.com/46065349/194589308-585e33b5-b598-40bf-a012-d2d63022fbc5.png">

**Comment by xhayper** [comment] 2022-10-07 15:18
woops wrong image

**Comment by xhayper** [comment] 2022-10-07 15:19
delete your node_modules folder
```json
{
  "dependencies": {
    "coc-clangd": ">=0.25.0",
    "coc-css": ">=1.3.0",
    "coc-emmet": ">=1.1.6",
    "coc-java": ">=1.5.5",
    "coc-json": ">=1.6.1",
    "coc-lua": ">=1.0.1",
    "coc-pyright": ">=1.1.271",
    "coc-rust-analyzer": ">=0.68.1",
    "coc-sh": ">=0.7.0",
    "coc-snippets": ">=3.1.2",
    "coc-texlab": ">=3.2.0",
    "coc-tsserver": ">=1.11.9",
    "coc-vimlsp": ">=0.12.8",
    "coc-word": ">=1.2.2",
    "coc-discord-rpc": "leonardssh/coc-discord-rpc#build-dev"
  }
}
```

and npm install

**Comment by xhayper** [comment] 2022-10-07 15:20
if that doesn't work
do below and send me both output

> can you go to `/Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transports/IPC.js` and add `console.log(socketPath)` to line 86

> find /private/var/folders -name "*discord-ipc*" 2> /dev/null

**Comment by SirCharlieMars** [comment] 2022-10-07 15:23
<img width="1330" alt="CleanShot 2022-10-07 at 10 22 31@2x" src="https://user-images.githubusercontent.com/31679231/194590281-394452a7-649c-4267-b269-816d1d09899f.png">


> find /private/var/folders -name "discord-ipc" 2> /dev/null
no folder

**Comment by xhayper** [comment] 2022-10-07 15:26
alrighty, so the problem is, we dont how where your discord rpc path is

**Comment by SirCharlieMars** [comment] 2022-10-07 15:27
I found it :)

```
## versions

vim version: NVIM v0.9.0-dev-1257-gcfdb4cbad-dirty
node version: v16.16.0
coc.nvim version: 0.0.82-9766fde1 2022-10-07 21:45:48 +0800
coc.nvim directory: /Users/charlie/.local/share/nvim/site/pack/packer/start/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-10-07T10:27:14.818 INFO (pid:33085) [coc-discord-rpc] - === Extension activated ===
2022-10-07T10:27:14.820 INFO (pid:33085) [coc-discord-rpc] - Extension Name: dev.coc-discord-rpc.
2022-10-07T10:27:14.820 INFO (pid:33085) [coc-discord-rpc] - Extension Version: 0.0.0.
2022-10-07T10:27:14.820 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.821 INFO (pid:33085) [plugin] - coc.nvim initialized with node: v16.16.0 after 106ms
2022-10-07T10:27:14.823 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.823 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.823 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.823 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.824 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.824 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.824 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.824 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.824 INFO (pid:33085) [extension:coc-discord-rpc] - 
2022-10-07T10:27:14.824 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-0
2022-10-07T10:27:14.825 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-1
2022-10-07T10:27:14.825 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-2
2022-10-07T10:27:14.826 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-3
2022-10-07T10:27:14.826 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-4
2022-10-07T10:27:14.826 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-5
2022-10-07T10:27:14.827 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-6
2022-10-07T10:27:14.827 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-7
2022-10-07T10:27:14.827 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-8
2022-10-07T10:27:14.827 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/discord-ipc-9
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-0
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-1
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-2
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-3
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-4
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-5
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-6
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-7
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-8
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/snap.discord/discord-ipc-9
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-0
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-1
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-2
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-3
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-4
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-5
2022-10-07T10:27:14.828 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-6
2022-10-07T10:27:14.829 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-7
2022-10-07T10:27:14.829 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-8
2022-10-07T10:27:14.829 INFO (pid:33085) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/JmhDYb/app/com.discordapp.Discord/discord-ipc-9
2022-10-07T10:27:14.829 ERROR (pid:33085) [server] - unhandledRejection  Promise {
  <rejected> RPC_COULD_NOT_CONNECT: Could not connect
      at /Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:109:20
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 2
  }
} RPC_COULD_NOT_CONNECT: Could not connect
    at /Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:109:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2
}
2022-10-07T10:27:15.004 INFO (pid:33085) [attach] - receive notification: highlight []
2022-10-07T10:27:23.637 INFO (pid:33085) [attach] - receive notification: showInfo []

```

**Comment by xhayper** [comment] 2022-10-07 15:29
what does
`find /private/var/folders -name "discord-ipc" 2> /dev/null` say?

**Comment by SirCharlieMars** [comment] 2022-10-07 15:31
No output.

**Comment by xhayper** [comment] 2022-10-07 15:32
alright, we have no idea where your discord-rpc part is, neither does the code, what we have to figure out is where discord-rpc is

**Comment by xhayper** [comment] 2022-10-07 15:33
OH WAIT I GOT THE COMMAND WRONG, can you try
`find /private/var/folders -name "*discord-ipc*" 2> /dev/null`

**Comment by SirCharlieMars** [comment] 2022-10-07 15:33
<img width="716" alt="image" src="https://user-images.githubusercontent.com/31679231/194592313-1f061141-5d51-4670-9253-7f6d9926a097.png">
found

**Comment by xhayper** [comment] 2022-10-07 15:34
yeah give me a moment while i work on this bug

**Comment by xhayper** [comment] 2022-10-07 15:37
can you go to `/Users/charlie/.config/coc/extensions/node_modules/coc-discord-rpc/dist/constants.js` and add `console.log(prefix)` to the line before `if (["nvim", "vim"]`

**Comment by xhayper** [comment] 2022-10-07 15:47
ok, so, i don't know how "nvim.charlie/of219P" managed to get there, it caused a problem

**Comment by xhayper** [comment] 2022-10-07 15:47
i just pushed a fix out, give it a moment before running `npm install`

**Comment by xhayper** [comment] 2022-10-07 15:49
alright install now

**Comment by xhayper** [comment] 2022-10-07 16:00
lmk if it work

**Comment by SirCharlieMars** [comment] 2022-10-07 16:02
Nope :(

```
## versions

vim version: NVIM v0.9.0-dev-1257-gcfdb4cbad-dirty
node version: v16.16.0
coc.nvim version: 0.0.82-9766fde1 2022-10-07 21:45:48 +0800
coc.nvim directory: /Users/charlie/.local/share/nvim/site/pack/packer/start/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-10-07T11:02:12.394 INFO (pid:40815) [coc-discord-rpc] - === Extension activated ===
2022-10-07T11:02:12.395 INFO (pid:40815) [coc-discord-rpc] - Extension Name: dev.coc-discord-rpc.
2022-10-07T11:02:12.395 INFO (pid:40815) [coc-discord-rpc] - Extension Version: 0.0.0.
2022-10-07T11:02:12.395 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.397 INFO (pid:40815) [plugin] - coc.nvim initialized with node: v16.16.0 after 90ms
2022-10-07T11:02:12.399 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.399 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - 
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.400 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-0
2022-10-07T11:02:12.401 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.401 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-1
2022-10-07T11:02:12.402 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.402 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-2
2022-10-07T11:02:12.402 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.402 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-3
2022-10-07T11:02:12.402 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.402 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-4
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-5
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-6
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-7
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-8
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV
2022-10-07T11:02:12.403 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/discord-ipc-9
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-0
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-1
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-2
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-3
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-4
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-5
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-6
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-7
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-8
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/snap.discord/discord-ipc-9
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-0
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-1
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-2
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-3
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-4
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-5
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-6
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-7
2022-10-07T11:02:12.404 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-8
2022-10-07T11:02:12.405 INFO (pid:40815) [extension:coc-discord-rpc] - /private/var/folders/bk/xdf025qx2svc8z2_t0znh5jr0000gn/T/nvim.charlie/OCskCV/app/com.discordapp.Discord/discord-ipc-9
2022-10-07T11:02:12.405 ERROR (pid:40815) [server] - unhandledRejection  Promise {
  <rejected> RPC_COULD_NOT_CONNECT: Could not connect
      at /Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:109:20
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    code: 2
  }
} RPC_COULD_NOT_CONNECT: Could not connect
    at /Users/charlie/.config/coc/extensions/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:109:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2
}
2022-10-07T11:02:12.579 INFO (pid:40815) [attach] - receive notification: highlight []
2022-10-07T11:02:15.212 INFO (pid:40815) [attach] - receive notification: showInfo []

```

**Comment by xhayper** [comment] 2022-10-07 16:03
can you see `for (const p of prefixSplitted) {` in constants.js?

**Comment by xhayper** [comment] 2022-10-07 16:07
try reinstall now (remove node_modules and package-lock.json)

**Comment by SirCharlieMars** [comment] 2022-10-07 16:15
It works!

**Closed** 2022-10-08 03:54 UTC
Labels: bug
