### ISSUE TITLE
Workspace never found

### ISSUE THREAD

**Issue by l-zeuch** [leonardssh/coc-discord-rpc#57] opened 2021-10-11 15:59 UTC
**NVim version:**
v0.4.4 Release

**OS**
GNU/Linux Debian 11 x86_64, kernel 5.10.0-9-amd64

**Steps to reproduce**
```shell
mkdir temp-test
cd temp-test
nvim .
```

**Expected result**
The RPC shows "temp-test" as workspace_folder.

**Actual result**
"No workspace" is shown instead.

**Configuration**
```json
{
"rpc.enabled": true,
"rpc.ignoreWorkspaces": [],
"rpc.workspaceElapsedTime": true,
"rpc.checkIdle": true,
"rpc.idleTimeout": 300,
"rpc.idleText": "😴 Idling...",
"rpc.problemsText": "{count} problems found",
"rpc.detailsEditing": "📂 {workspace_folder}",
"rpc.detailsViewing": "📂 {workspace_folder}",
"rpc.lowerDetailsViewing": "📄 {file_name} • {total_lines} lines",
"rpc.lowerDetailsEditing": "📄 {file_name} • {total_lines} lines",
"rpc.largeImage": "Editing a {Lang} file"
}
```

**Additional context**
Your VSCode extension works perfectly fine with the same settings (except of course with VSCode instead of NVim), which is quite strange??

**Comment by xhayper** [comment] 2022-10-08 04:27
This was caused by the extension relying on file to get workspace, since you are opening directory listing / untitled file, it can't figure out where it belong causing this bug, i will try to find a fix for this.

**Comment by xhayper** [comment] 2022-10-08 04:30
What i can do is make it check for file's workspace folder, THEN i can check for current working directory and THEN fallback to no workspace, i will let you decided if that is a good idea

**Comment by xhayper** [comment] 2022-10-08 04:35
i will add `rpc.useCWDAsFallback` as config, so it will resolve this, it will be disabled by default but you can enable it

**Closed** 2022-10-08 04:37 UTC
Labels: bug

**Comment by l-zeuch** [comment] 2022-10-08 11:27
Thank you! That works beautifully.

**Comment by xhayper** [comment] 2022-10-08 11:53
No problem, sorry for being a year late
